# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- testMobileApp

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  solutionName: 'Crypollet.sln'

jobs:

- job : BuildAndroid
  displayName : 'Build Android App'

  steps:

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solutionName)'
      
  - script:
       ls
    displayName: 'show contents in file'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'


- job : BuildiOS
  displayName : "Build iOS App"
  
  steps:

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
     restoreSolution: '$(solutionName)'

  - task: XamariniOS@2
    inputs:
      solutionFile: '$(solutionName)'
      configuration: '$(buildConfiguration)'
      packageApp: false
      buildForSimulator: true
      runNugetRestore: false
